### ISSUE TITLE
The required file of Evaluation_qmeandisco method

### ISSUE THREAD

**Issue by wt12318** [PhilippJunk/homelette#2]
Hi,

I am confused about the three files required by `Evaluation_qmeandisco`(https://homelette.readthedocs.io/en/latest/evaluation.html#homelette.evaluation.Evaluation_qmeandisco):

```
Requires the following valid entries in the model.info dictionary:

- accpro_file (.acc file)
- psipred_file (.horiz file)
- disco_file (generated by qmean.DisCoContainer.Save)
```

How to generated these files? Thank you.

Tao Wu

**Comment by PhilippJunk** [comment]
Hi, 

generating the files necessary to run `Evaluation_qmeandisco` is indeed a bit confusing, sorry if the documentation is not detailed enough on this. 

For the full QMEANDisCo prediction, you need 
- Solvent accessibility predictions generated with ACCPro.
- Secondary structure predictions generated with PSIPRED.
- Distance constraints of related structures created with the `qmean` python package.

All of these need to be only run once for a target sequence, which is why they were not included in the Evaluation method itself (which would re-run it for each generated model).

ACCPro can be downloaded from [here](https://download.igb.uci.edu/#accpro), there should also be some documentation for it.

PSIPRED can be downloaded from [here](https://github.com/psipred/psipred).

QMEAN is already installed in the docker container. However, there is no online documentation, you have to build it yourself. Instructions along with the source are [here](https://git.scicore.unibas.ch/schwede/QMEAN). In the documentation, there is an explanation how to generate and save the `disco_file`.

For ACCPro and PSIPRED, I am pretty sure that there are web servers available to generate the necessary files. If you only have a few target structures, it might be easier to use those as setting up these programs was a bit tedious if I remember correctly.

Hope this was helpful, 
Philipp
